<?php

/**
 * Implements hook_system_info_alter()
 * Adds a new "splash" region to the current theme
 */
function splash_block_system_info_alter(&$info, $file){
  global $custom_theme;    
 
  // If non-default theme configuration has been selected, set the custom theme.
  $custom_theme = isset ($theme) ? $theme : variable_get('theme_default', 'bartik');
 
  if ($file->name == $custom_theme){
    $info['regions'] = array_merge($info['regions'],  array('splash' => t('Splash')));
  } 
}

/**
 * Implements hook_page_alter()
 */
function splash_block_page_build(&$page) {

	if (!isset($page['splash'])) {
		return;
	}
	
  $path = drupal_get_path('module', 'splash_block');
	
	$page['page_bottom']['splash'] = array(
    '#attached' => array(),
  );
  $attached = &$page['page_bottom']['splash']['#attached'];
  $options = array('every_page' => TRUE, 'group' => JS_THEME);

  $attached['css'][$path . '/splash.css'] = $options;
  $attached['js'][$path . '/splash.js'] = $options;
	
	$splash_block = array_shift(array_values($page['splash']));	
	$bid = $splash_block['#block']->bid;
	
	$page['page_bottom']['splash']['#markup'] .= '<div id="splash-content"><div class="block" id="' . $bid . '">' . $splash_block['#markup'] . '</div></div>';
	
	drupal_add_js(libraries_get_path('jstorage') . '/jstorage.min.js', array('group' => JS_THEME, 'every_page' => TRUE));
	drupal_add_js(libraries_get_path('json2') . '/json2.js', array('group' => JS_THEME, 'every_page' => TRUE));
	drupal_add_js('
		jQuery(document).ready(function() {
			jQuery(window).load(function() {
				jQuery("#splash-content .block").each(
					function(index) {
						var id = jQuery(this).attr("id");
						var value = jQuery.jStorage.get(id);
						var ttl = jQuery.jStorage.getTTL(id);

						if(!value || ttl == 0){
							value = 1;

							var splash = jQuery(this).html();
							modal.open({content: splash, width: "400px"});

							jQuery.jStorage.set(id,value);
							jQuery.jStorage.setTTL(id,1209600000);
							// two weeks = 1209600000
						}
					}
				);
				jQuery("#splash-content").remove();
			});
		});
	', 'inline');
}
